/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DiscountCode } from "./DiscountCode";
import { DiscountCodeCountArgs } from "./DiscountCodeCountArgs";
import { DiscountCodeFindManyArgs } from "./DiscountCodeFindManyArgs";
import { DiscountCodeFindUniqueArgs } from "./DiscountCodeFindUniqueArgs";
import { CreateDiscountCodeArgs } from "./CreateDiscountCodeArgs";
import { UpdateDiscountCodeArgs } from "./UpdateDiscountCodeArgs";
import { DeleteDiscountCodeArgs } from "./DeleteDiscountCodeArgs";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { DiscountCodeService } from "../discountCode.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DiscountCode)
export class DiscountCodeResolverBase {
  constructor(
    protected readonly service: DiscountCodeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "read",
    possession: "any",
  })
  async _discountCodesMeta(
    @graphql.Args() args: DiscountCodeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DiscountCode])
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "read",
    possession: "any",
  })
  async discountCodes(
    @graphql.Args() args: DiscountCodeFindManyArgs
  ): Promise<DiscountCode[]> {
    return this.service.discountCodes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DiscountCode, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "read",
    possession: "own",
  })
  async discountCode(
    @graphql.Args() args: DiscountCodeFindUniqueArgs
  ): Promise<DiscountCode | null> {
    const result = await this.service.discountCode(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DiscountCode)
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "create",
    possession: "any",
  })
  async createDiscountCode(
    @graphql.Args() args: CreateDiscountCodeArgs
  ): Promise<DiscountCode> {
    return await this.service.createDiscountCode({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DiscountCode)
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "update",
    possession: "any",
  })
  async updateDiscountCode(
    @graphql.Args() args: UpdateDiscountCodeArgs
  ): Promise<DiscountCode | null> {
    try {
      return await this.service.updateDiscountCode({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DiscountCode)
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "delete",
    possession: "any",
  })
  async deleteDiscountCode(
    @graphql.Args() args: DeleteDiscountCodeArgs
  ): Promise<DiscountCode | null> {
    try {
      return await this.service.deleteDiscountCode(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Order], { name: "orders" })
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  async findOrders(
    @graphql.Parent() parent: DiscountCode,
    @graphql.Args() args: OrderFindManyArgs
  ): Promise<Order[]> {
    const results = await this.service.findOrders(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
