/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DiscountCodeService } from "../discountCode.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DiscountCodeCreateInput } from "./DiscountCodeCreateInput";
import { DiscountCode } from "./DiscountCode";
import { DiscountCodeFindManyArgs } from "./DiscountCodeFindManyArgs";
import { DiscountCodeWhereUniqueInput } from "./DiscountCodeWhereUniqueInput";
import { DiscountCodeUpdateInput } from "./DiscountCodeUpdateInput";
import { OrderFindManyArgs } from "../../order/base/OrderFindManyArgs";
import { Order } from "../../order/base/Order";
import { OrderWhereUniqueInput } from "../../order/base/OrderWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DiscountCodeControllerBase {
  constructor(
    protected readonly service: DiscountCodeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DiscountCode })
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDiscountCode(
    @common.Body() data: DiscountCodeCreateInput
  ): Promise<DiscountCode> {
    return await this.service.createDiscountCode({
      data: data,
      select: {
        code: true,
        createdAt: true,
        discountPercentage: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [DiscountCode] })
  @ApiNestedQuery(DiscountCodeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async discountCodes(@common.Req() request: Request): Promise<DiscountCode[]> {
    const args = plainToClass(DiscountCodeFindManyArgs, request.query);
    return this.service.discountCodes({
      ...args,
      select: {
        code: true,
        createdAt: true,
        discountPercentage: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DiscountCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async discountCode(
    @common.Param() params: DiscountCodeWhereUniqueInput
  ): Promise<DiscountCode | null> {
    const result = await this.service.discountCode({
      where: params,
      select: {
        code: true,
        createdAt: true,
        discountPercentage: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DiscountCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDiscountCode(
    @common.Param() params: DiscountCodeWhereUniqueInput,
    @common.Body() data: DiscountCodeUpdateInput
  ): Promise<DiscountCode | null> {
    try {
      return await this.service.updateDiscountCode({
        where: params,
        data: data,
        select: {
          code: true,
          createdAt: true,
          discountPercentage: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DiscountCode })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDiscountCode(
    @common.Param() params: DiscountCodeWhereUniqueInput
  ): Promise<DiscountCode | null> {
    try {
      return await this.service.deleteDiscountCode({
        where: params,
        select: {
          code: true,
          createdAt: true,
          discountPercentage: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/orders")
  @ApiNestedQuery(OrderFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Order",
    action: "read",
    possession: "any",
  })
  async findOrders(
    @common.Req() request: Request,
    @common.Param() params: DiscountCodeWhereUniqueInput
  ): Promise<Order[]> {
    const query = plainToClass(OrderFindManyArgs, request.query);
    const results = await this.service.findOrders(params.id, {
      ...query,
      select: {
        createdAt: true,
        customerAddress: true,
        customerEmail: true,
        customerMapLocation: true,
        customerName: true,
        customerPhoneNumber: true,

        discountCode: {
          select: {
            id: true,
          },
        },

        id: true,

        offer: {
          select: {
            id: true,
          },
        },

        totalCost: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "update",
    possession: "any",
  })
  async connectOrders(
    @common.Param() params: DiscountCodeWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        connect: body,
      },
    };
    await this.service.updateDiscountCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "update",
    possession: "any",
  })
  async updateOrders(
    @common.Param() params: DiscountCodeWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        set: body,
      },
    };
    await this.service.updateDiscountCode({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/orders")
  @nestAccessControl.UseRoles({
    resource: "DiscountCode",
    action: "update",
    possession: "any",
  })
  async disconnectOrders(
    @common.Param() params: DiscountCodeWhereUniqueInput,
    @common.Body() body: OrderWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      orders: {
        disconnect: body,
      },
    };
    await this.service.updateDiscountCode({
      where: params,
      data,
      select: { id: true },
    });
  }
}
